### ISSUE TITLE
Prediction Function

### ISSUE THREAD

**Issue by easyautoml** [easyautoml/easyml#17]
1. About UI.
Instead of having 2 button, I think it will be better if we put option external or internal into Creadit Prediction frame.
![image](https://user-images.githubusercontent.com/100541539/163924667-ed38a225-aba0-4be3-a233-f9f9b9675d3b.png)

2. About function upload data.
Predict data should not be showed as external data. Every time when I predict from external data, that file become internal data and it's not good because generally, Predict data dont have target and not used to build model.

![image](https://user-images.githubusercontent.com/100541539/163924914-35c5b5fb-ccfb-4d9b-be50-bcb0e606e317.png)

3. About Async.
Instead run upload task before run predict task, we should customize predict function to predict in 2 scenario, one with internal and other with external data.

**Comment by redcican** [comment]
you are right, maybe we can filter those data and hide them in datasource management page?

**Comment by redcican** [comment]
So my idea was to add a filed for the model "File" like "is_external" so we can filter them, what would you say?

**Comment by easyautoml** [comment]
Already complete the function.
https://github.com/easyautoml/easyml/commit/0a97163bcdd06e13e5ae81a715f6dd1c08691eab
