### ISSUE TITLE
After uploading the file, the status symbol keeps as spinner, need manually refresh the page

### ISSUE THREAD

**Issue by redcican** [easyautoml/easyml#2]
After I uploaded the file, the status symbol keeps as spinner, it is kind of confusing for user, is there any bugs connecting to the celery?

And can you add a button in Data Management page, after uploading file we can directly go to experiment creating page. Otherwise, user may feel confuse what to do in next step.

**Comment by easyautoml** [comment]
Actually, it isn't bug. So shame that we need reload (f5) the page to update real status. I might use Ajax to get status through API, that could help update status automatically after complete.

> And can you add a button in Data Management page, after uploading file we can directly go to experiment creating page. Otherwise, user may feel confuse what to do in next step.

Good idea! Should we create a button inside the list of file.
File                        
titanic.csv        [Button Create Experiemnt]

**Comment by easyautoml** [comment]
@redcican    This problem was sloved. You can check at dev branch.
